name: Build and push

on:
  push:
  
  schedule:
    - cron:  '0 2 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build -t chrisnharvey/goserve:latest .

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        email: ${{ secrets.DOCKER_EMAIL }}
        
    - name: Push image to registry
      run: docker push chrisnharvey/goserve:latest